// <auto-generated />
using System;
using Gbazaar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GBazaar.Migrations
{
    [DbContext(typeof(ProcurementContext))]
    [Migration("20251130093028_xxx")]
    partial class xxx
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GBazaar.Models.ApprovalHistory", b =>
                {
                    b.Property<int>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryID"));

                    b.Property<DateTime>("ActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<int>("ApprovalLevel")
                        .HasColumnType("int");

                    b.Property<int>("ApproverID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PRID")
                        .HasColumnType("int");

                    b.HasKey("HistoryID");

                    b.HasIndex("ApproverID");

                    b.HasIndex("PRID");

                    b.ToTable("ApprovalHistories");
                });

            modelBuilder.Entity("GBazaar.Models.ApprovalRule", b =>
                {
                    b.Property<int>("RuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleID"));

                    b.Property<int>("ApprovalLevel")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RequiredRoleID")
                        .HasColumnType("int");

                    b.HasKey("RuleID");

                    b.HasIndex("RequiredRoleID");

                    b.HasIndex("MinAmount", "MaxAmount", "RequiredRoleID", "ApprovalLevel")
                        .IsUnique()
                        .HasFilter("[MaxAmount] IS NOT NULL");

                    b.ToTable("ApprovalRules");
                });

            modelBuilder.Entity("GBazaar.Models.Attachment", b =>
                {
                    b.Property<int>("AttachmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentID"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EntityID")
                        .HasColumnType("int");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UploadedByUserID")
                        .HasColumnType("int");

                    b.HasKey("AttachmentID");

                    b.HasIndex("UploadedByUserID");

                    b.HasIndex("EntityType", "EntityID", "FileName")
                        .IsUnique();

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("GBazaar.Models.Budget", b =>
                {
                    b.Property<int>("BudgetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetID"));

                    b.Property<decimal?>("AmountCommitted")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBudget")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("BudgetID");

                    b.HasIndex("DepartmentID", "FiscalYear")
                        .IsUnique();

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("GBazaar.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("BudgetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ManagerID")
                        .HasColumnType("int");

                    b.HasKey("DepartmentID");

                    b.HasIndex("BudgetCode")
                        .IsUnique();

                    b.HasIndex("ManagerID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("GBazaar.Models.GoodsReceipt", b =>
                {
                    b.Property<int>("ReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptID"));

                    b.Property<DateTime>("DateReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("POID")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ReceivedByUserID")
                        .HasColumnType("int");

                    b.HasKey("ReceiptID");

                    b.HasIndex("POID");

                    b.HasIndex("ReceivedByUserID");

                    b.ToTable("GoodsReceipts");
                });

            modelBuilder.Entity("GBazaar.Models.GoodsReceiptItem", b =>
                {
                    b.Property<int>("GRItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GRItemID"));

                    b.Property<int>("GRID")
                        .HasColumnType("int");

                    b.Property<int?>("GoodsReceiptItemGRItemID")
                        .HasColumnType("int");

                    b.Property<int>("POItemID")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("GRItemID");

                    b.HasIndex("GRID");

                    b.HasIndex("GoodsReceiptItemGRItemID");

                    b.HasIndex("POItemID");

                    b.ToTable("GoodsReceiptItems");
                });

            modelBuilder.Entity("GBazaar.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceID"));

                    b.Property<decimal?>("AmountDue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("POID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<int?>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentStatusID")
                        .HasColumnType("int");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.HasKey("InvoiceID");

                    b.HasIndex("POID");

                    b.HasIndex("SupplierID");

                    b.HasIndex("InvoiceNumber", "SupplierID")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("GBazaar.Models.POItem", b =>
                {
                    b.Property<int>("POItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("POItemID"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("POID")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("POItemID");

                    b.HasIndex("POID");

                    b.ToTable("POItems");
                });

            modelBuilder.Entity("GBazaar.Models.PRItem", b =>
                {
                    b.Property<int>("PRItemID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("PRID")
                        .HasColumnType("int");

                    b.Property<string>("PRItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("SupplierID")
                        .HasColumnType("int");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PRItemID");

                    b.HasIndex("PRID");

                    b.HasIndex("SupplierID");

                    b.ToTable("PRItems");
                });

            modelBuilder.Entity("GBazaar.Models.PaymentTerm", b =>
                {
                    b.Property<int>("PaymentTermID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentTermID"));

                    b.Property<int>("DaysDue")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentTermID");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("PaymentTerms");
                });

            modelBuilder.Entity("GBazaar.Models.Permission", b =>
                {
                    b.Property<int>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PermissionID");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("GBazaar.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ProductID");

                    b.HasIndex("SupplierID", "ProductName")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GBazaar.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("POID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("POID"));

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("datetime2");

                    b.Property<int>("POStatus")
                        .HasColumnType("int");

                    b.Property<int>("POStatusID")
                        .HasColumnType("int");

                    b.Property<int>("PRID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("RequiredDeliveryDate")
                        .HasColumnType("date");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.HasKey("POID");

                    b.HasIndex("PRID")
                        .IsUnique();

                    b.HasIndex("SupplierID");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("GBazaar.Models.PurchaseRequest", b =>
                {
                    b.Property<int>("PRID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PRID"));

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EstimatedTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Justification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PRStatus")
                        .HasColumnType("int");

                    b.Property<int>("PRStatusID")
                        .HasColumnType("int");

                    b.Property<int>("RequesterID")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierID")
                        .HasColumnType("int");

                    b.HasKey("PRID");

                    b.HasIndex("RequesterID");

                    b.HasIndex("SupplierID");

                    b.ToTable("PurchaseRequests");
                });

            modelBuilder.Entity("GBazaar.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GBazaar.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("PermissionID")
                        .HasColumnType("int");

                    b.HasKey("RoleID", "PermissionID");

                    b.HasIndex("PermissionID");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("GBazaar.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"));

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaymentTermID")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaxID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SupplierID");

                    b.HasIndex("PaymentTermID");

                    b.HasIndex("SupplierName")
                        .IsUnique();

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("GBazaar.Models.SupplierRating", b =>
                {
                    b.Property<int>("RatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingID"));

                    b.Property<string>("FeedBack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("POID")
                        .HasColumnType("int");

                    b.Property<int>("RatedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("RatingScore")
                        .HasColumnType("int");

                    b.HasKey("RatingID");

                    b.HasIndex("POID");

                    b.HasIndex("RatedByUserID");

                    b.ToTable("SupplierRatings");
                });

            modelBuilder.Entity("GBazaar.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GBazaar.Models.ApprovalHistory", b =>
                {
                    b.HasOne("GBazaar.Models.User", "Approver")
                        .WithMany("ApprovalHistories")
                        .HasForeignKey("ApproverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBazaar.Models.PurchaseRequest", "PurchaseRequest")
                        .WithMany("ApprovalHistories")
                        .HasForeignKey("PRID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("PurchaseRequest");
                });

            modelBuilder.Entity("GBazaar.Models.ApprovalRule", b =>
                {
                    b.HasOne("GBazaar.Models.Role", "RequiredRole")
                        .WithMany("ApprovalRules")
                        .HasForeignKey("RequiredRoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequiredRole");
                });

            modelBuilder.Entity("GBazaar.Models.Attachment", b =>
                {
                    b.HasOne("GBazaar.Models.User", "Uploader")
                        .WithMany("Attachments")
                        .HasForeignKey("UploadedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("GBazaar.Models.Budget", b =>
                {
                    b.HasOne("GBazaar.Models.Department", "Department")
                        .WithMany("Budgets")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GBazaar.Models.Department", b =>
                {
                    b.HasOne("GBazaar.Models.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("GBazaar.Models.GoodsReceipt", b =>
                {
                    b.HasOne("GBazaar.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("GoodsReceipts")
                        .HasForeignKey("POID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBazaar.Models.User", "Receiver")
                        .WithMany("GoodsReceipts")
                        .HasForeignKey("ReceivedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("GBazaar.Models.GoodsReceiptItem", b =>
                {
                    b.HasOne("GBazaar.Models.GoodsReceipt", "GoodsReceipt")
                        .WithMany("GoodsReceiptItems")
                        .HasForeignKey("GRID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBazaar.Models.GoodsReceiptItem", null)
                        .WithMany("GoodsReceiptItems")
                        .HasForeignKey("GoodsReceiptItemGRItemID");

                    b.HasOne("GBazaar.Models.POItem", "POItem")
                        .WithMany()
                        .HasForeignKey("POItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoodsReceipt");

                    b.Navigation("POItem");
                });

            modelBuilder.Entity("GBazaar.Models.Invoice", b =>
                {
                    b.HasOne("GBazaar.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Invoices")
                        .HasForeignKey("POID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBazaar.Models.Supplier", "Supplier")
                        .WithMany("Invoices")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GBazaar.Models.POItem", b =>
                {
                    b.HasOne("GBazaar.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("POItems")
                        .HasForeignKey("POID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("GBazaar.Models.PRItem", b =>
                {
                    b.HasOne("GBazaar.Models.PurchaseRequest", "PurchaseRequest")
                        .WithMany("PRItems")
                        .HasForeignKey("PRID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GBazaar.Models.Product", "Product")
                        .WithMany("PRItems")
                        .HasForeignKey("PRItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBazaar.Models.Supplier", "Supplier")
                        .WithMany("PRItems")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("PurchaseRequest");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GBazaar.Models.Product", b =>
                {
                    b.HasOne("GBazaar.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GBazaar.Models.PurchaseOrder", b =>
                {
                    b.HasOne("GBazaar.Models.PurchaseRequest", "PurchaseRequest")
                        .WithOne("PurchaseOrder")
                        .HasForeignKey("GBazaar.Models.PurchaseOrder", "PRID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBazaar.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseRequest");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GBazaar.Models.PurchaseRequest", b =>
                {
                    b.HasOne("GBazaar.Models.User", "Requester")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("RequesterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBazaar.Models.Supplier", "Supplier")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Requester");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GBazaar.Models.RolePermission", b =>
                {
                    b.HasOne("GBazaar.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBazaar.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GBazaar.Models.Supplier", b =>
                {
                    b.HasOne("GBazaar.Models.PaymentTerm", "PaymentTerm")
                        .WithMany("Suppliers")
                        .HasForeignKey("PaymentTermID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentTerm");
                });

            modelBuilder.Entity("GBazaar.Models.SupplierRating", b =>
                {
                    b.HasOne("GBazaar.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("SupplierRatings")
                        .HasForeignKey("POID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBazaar.Models.User", "Rater")
                        .WithMany("SupplierRatings")
                        .HasForeignKey("RatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Rater");
                });

            modelBuilder.Entity("GBazaar.Models.User", b =>
                {
                    b.HasOne("GBazaar.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GBazaar.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GBazaar.Models.Department", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GBazaar.Models.GoodsReceipt", b =>
                {
                    b.Navigation("GoodsReceiptItems");
                });

            modelBuilder.Entity("GBazaar.Models.GoodsReceiptItem", b =>
                {
                    b.Navigation("GoodsReceiptItems");
                });

            modelBuilder.Entity("GBazaar.Models.PaymentTerm", b =>
                {
                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("GBazaar.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("GBazaar.Models.Product", b =>
                {
                    b.Navigation("PRItems");
                });

            modelBuilder.Entity("GBazaar.Models.PurchaseOrder", b =>
                {
                    b.Navigation("GoodsReceipts");

                    b.Navigation("Invoices");

                    b.Navigation("POItems");

                    b.Navigation("SupplierRatings");
                });

            modelBuilder.Entity("GBazaar.Models.PurchaseRequest", b =>
                {
                    b.Navigation("ApprovalHistories");

                    b.Navigation("PRItems");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("GBazaar.Models.Role", b =>
                {
                    b.Navigation("ApprovalRules");

                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GBazaar.Models.Supplier", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("PRItems");

                    b.Navigation("Products");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("PurchaseRequests");
                });

            modelBuilder.Entity("GBazaar.Models.User", b =>
                {
                    b.Navigation("ApprovalHistories");

                    b.Navigation("Attachments");

                    b.Navigation("GoodsReceipts");

                    b.Navigation("PurchaseRequests");

                    b.Navigation("SupplierRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
