// <auto-generated />
using System;
using Gbazaar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GBazaar.Migrations
{
    [DbContext(typeof(ProcurementContext))]
    partial class ProcurementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GBazaar.Models.ApprovalHistory", b =>
                {
                    b.Property<int>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryID"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ApprovalLevel")
                        .HasColumnType("int");

                    b.Property<int>("ApproverID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PRID")
                        .HasColumnType("int");

                    b.HasKey("HistoryID");

                    b.HasIndex("ApproverID");

                    b.HasIndex("PRID");

                    b.ToTable("ApprovalHistories");
                });

            modelBuilder.Entity("GBazaar.Models.ApprovalRule", b =>
                {
                    b.Property<int>("RuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleID"));

                    b.Property<int>("ApprovalLevel")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("RequiredRoleID")
                        .HasColumnType("int");

                    b.HasKey("RuleID");

                    b.HasIndex("RequiredRoleID");

                    b.ToTable("ApprovalRules");
                });

            modelBuilder.Entity("GBazaar.Models.Attachment", b =>
                {
                    b.Property<int>("AttachmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentID"));

                    b.Property<int>("EntityID")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("UploadedByUserID")
                        .HasColumnType("int");

                    b.HasKey("AttachmentID");

                    b.HasIndex("UploadedByUserID");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("GBazaar.Models.Budget", b =>
                {
                    b.Property<int>("BudgetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetID"));

                    b.Property<decimal?>("AmountCommited")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBudget")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("BudgetID");

                    b.HasIndex("DepartmentID")
                        .IsUnique();

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("GBazaar.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GBazaar.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("BudgetCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DepartmentID");

                    b.HasIndex("BudgetCode")
                        .IsUnique();

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("GBazaar.Models.GoodsReceipt", b =>
                {
                    b.Property<int>("ReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptID"));

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<int>("POID")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ReceivedByUserID")
                        .HasColumnType("int");

                    b.HasKey("ReceiptID");

                    b.HasIndex("POID");

                    b.HasIndex("ReceivedByUserID");

                    b.ToTable("GoodsReceipts");
                });

            modelBuilder.Entity("GBazaar.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceID"));

                    b.Property<decimal?>("AmountDue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("POID")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentStatusID")
                        .HasColumnType("int");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.HasKey("InvoiceID");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("POID");

                    b.HasIndex("PaymentStatusID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("GBazaar.Models.POStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("StatusType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.HasIndex("StatusType")
                        .IsUnique();

                    b.ToTable("POStatuses");
                });

            modelBuilder.Entity("GBazaar.Models.PRItem", b =>
                {
                    b.Property<int>("PRItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PRItemID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("PRID")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SubCategoryID")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PRItemID");

                    b.HasIndex("PRID");

                    b.HasIndex("SubCategoryID");

                    b.ToTable("PRItems");
                });

            modelBuilder.Entity("GBazaar.Models.PRStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("StatusType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.HasIndex("StatusType")
                        .IsUnique();

                    b.ToTable("PRStatuses");
                });

            modelBuilder.Entity("GBazaar.Models.PaymentStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("StatusType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusID");

                    b.HasIndex("StatusType")
                        .IsUnique();

                    b.ToTable("PaymentStatuses");
                });

            modelBuilder.Entity("GBazaar.Models.PaymentTerm", b =>
                {
                    b.Property<int>("PaymentTermsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentTermsID"));

                    b.Property<int>("DaysDue")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentTermsID");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.ToTable("PaymentTerms");
                });

            modelBuilder.Entity("GBazaar.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("POID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("POID"));

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("datetime2");

                    b.Property<int>("POStatusID")
                        .HasColumnType("int");

                    b.Property<int>("PRID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("RequiredDeliveryDate")
                        .HasColumnType("date");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.HasKey("POID");

                    b.HasIndex("POStatusID");

                    b.HasIndex("PRID")
                        .IsUnique();

                    b.HasIndex("SupplierID");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("GBazaar.Models.PurchaseRequest", b =>
                {
                    b.Property<int>("PRID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PRID"));

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EstimatedTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Justification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PRStatusID")
                        .HasColumnType("int");

                    b.Property<int>("RequesterID")
                        .HasColumnType("int");

                    b.HasKey("PRID");

                    b.HasIndex("PRStatusID");

                    b.HasIndex("RequesterID");

                    b.ToTable("PurchaseRequests");
                });

            modelBuilder.Entity("GBazaar.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GBazaar.Models.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategoryID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubCategoryID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("SubCategoryName")
                        .IsUnique();

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("GBazaar.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"));

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaymentTermsID")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TaxID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SupplierID");

                    b.HasIndex("PaymentTermsID");

                    b.HasIndex("SupplierName")
                        .IsUnique();

                    b.HasIndex("TaxID")
                        .IsUnique()
                        .HasFilter("[TaxID] IS NOT NULL");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("GBazaar.Models.SupplierRating", b =>
                {
                    b.Property<int>("RatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingID"));

                    b.Property<string>("FeedBack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("POID")
                        .HasColumnType("int");

                    b.Property<int>("RatedByUserID")
                        .HasColumnType("int");

                    b.Property<int>("RatingScore")
                        .HasColumnType("int");

                    b.HasKey("RatingID");

                    b.HasIndex("POID");

                    b.HasIndex("RatedByUserID");

                    b.ToTable("SupplierRatings");
                });

            modelBuilder.Entity("GBazaar.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GBazaar.Models.ApprovalHistory", b =>
                {
                    b.HasOne("GBazaar.Models.User", "Approver")
                        .WithMany("ApprovalHistories")
                        .HasForeignKey("ApproverID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBazaar.Models.PurchaseRequest", "PurchaseRequest")
                        .WithMany("ApprovalHistories")
                        .HasForeignKey("PRID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("PurchaseRequest");
                });

            modelBuilder.Entity("GBazaar.Models.ApprovalRule", b =>
                {
                    b.HasOne("GBazaar.Models.Role", "RequiredRole")
                        .WithMany("ApprovalRules")
                        .HasForeignKey("RequiredRoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequiredRole");
                });

            modelBuilder.Entity("GBazaar.Models.Attachment", b =>
                {
                    b.HasOne("GBazaar.Models.User", "Uploader")
                        .WithMany("Attachments")
                        .HasForeignKey("UploadedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("GBazaar.Models.Budget", b =>
                {
                    b.HasOne("GBazaar.Models.Department", "Department")
                        .WithOne("Budget")
                        .HasForeignKey("GBazaar.Models.Budget", "DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GBazaar.Models.GoodsReceipt", b =>
                {
                    b.HasOne("GBazaar.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("GoodsReceipts")
                        .HasForeignKey("POID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBazaar.Models.User", "Receiver")
                        .WithMany("GoodsReceipts")
                        .HasForeignKey("ReceivedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("GBazaar.Models.Invoice", b =>
                {
                    b.HasOne("GBazaar.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Invoices")
                        .HasForeignKey("POID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBazaar.Models.PaymentStatus", "PaymentStatus")
                        .WithMany("Invoices")
                        .HasForeignKey("PaymentStatusID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GBazaar.Models.Supplier", "Supplier")
                        .WithMany("Invoices")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentStatus");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GBazaar.Models.PRItem", b =>
                {
                    b.HasOne("GBazaar.Models.PurchaseRequest", "PurchaseRequest")
                        .WithMany("PRItems")
                        .HasForeignKey("PRID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GBazaar.Models.SubCategory", "SubCategory")
                        .WithMany("PRItems")
                        .HasForeignKey("SubCategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseRequest");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("GBazaar.Models.PurchaseOrder", b =>
                {
                    b.HasOne("GBazaar.Models.POStatus", "POStatus")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("POStatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBazaar.Models.PurchaseRequest", "PurchaseRequest")
                        .WithOne("PurchaseOrder")
                        .HasForeignKey("GBazaar.Models.PurchaseOrder", "PRID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBazaar.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("POStatus");

                    b.Navigation("PurchaseRequest");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("GBazaar.Models.PurchaseRequest", b =>
                {
                    b.HasOne("GBazaar.Models.PRStatus", "PRStatus")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("PRStatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBazaar.Models.User", "Requester")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("RequesterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PRStatus");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("GBazaar.Models.SubCategory", b =>
                {
                    b.HasOne("GBazaar.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GBazaar.Models.Supplier", b =>
                {
                    b.HasOne("GBazaar.Models.PaymentTerm", "PaymentTerm")
                        .WithMany("Suppliers")
                        .HasForeignKey("PaymentTermsID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentTerm");
                });

            modelBuilder.Entity("GBazaar.Models.SupplierRating", b =>
                {
                    b.HasOne("GBazaar.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("SupplierRatings")
                        .HasForeignKey("POID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GBazaar.Models.User", "Rater")
                        .WithMany("SupplierRatings")
                        .HasForeignKey("RatedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Rater");
                });

            modelBuilder.Entity("GBazaar.Models.User", b =>
                {
                    b.HasOne("GBazaar.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GBazaar.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GBazaar.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("GBazaar.Models.Department", b =>
                {
                    b.Navigation("Budget");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GBazaar.Models.POStatus", b =>
                {
                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("GBazaar.Models.PRStatus", b =>
                {
                    b.Navigation("PurchaseRequests");
                });

            modelBuilder.Entity("GBazaar.Models.PaymentStatus", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("GBazaar.Models.PaymentTerm", b =>
                {
                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("GBazaar.Models.PurchaseOrder", b =>
                {
                    b.Navigation("GoodsReceipts");

                    b.Navigation("Invoices");

                    b.Navigation("SupplierRatings");
                });

            modelBuilder.Entity("GBazaar.Models.PurchaseRequest", b =>
                {
                    b.Navigation("ApprovalHistories");

                    b.Navigation("PRItems");

                    b.Navigation("PurchaseOrder")
                        .IsRequired();
                });

            modelBuilder.Entity("GBazaar.Models.Role", b =>
                {
                    b.Navigation("ApprovalRules");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("GBazaar.Models.SubCategory", b =>
                {
                    b.Navigation("PRItems");
                });

            modelBuilder.Entity("GBazaar.Models.Supplier", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("GBazaar.Models.User", b =>
                {
                    b.Navigation("ApprovalHistories");

                    b.Navigation("Attachments");

                    b.Navigation("GoodsReceipts");

                    b.Navigation("PurchaseRequests");

                    b.Navigation("SupplierRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
